ubuntu2004_openmpi:
  image: gitlab-registry.mpcdf.mpg.de/khr/docker/gempic/ubuntu2004
  only:
    - master
  script:
    - mkdir build
    - export BUILD_DIR=`readlink -f ./build`
    - cd scripts
    - bash gempic_ci.sh
  tags:
    - avx2
    - docker

