ubuntu2004_openmpi_3D:
  image: gitlab-registry.mpcdf.mpg.de/khr/docker/gempic/ubuntu2004
  script:
    - mkdir build
    - export BUILD_DIR=`readlink -f ./build`
    - cd scripts
    - bash gempic3D_ci.sh
  tags:
    - avx2
    - docker
    
image: gitlab-registry.mpcdf.mpg.de/mpcdf/module-image

build-gcc-gpu:
  tags:
    - gpu 
  script:
    - cd scripts
    - sbatch --wait ci_raven_gpu_jobscript.sh && cat ci_job.out || cat ci_job.out

# if runner offline: login to raven and type tmux; ./bin/gitlab-runner run; ctrl B D 
