ubuntu2004_openmpi_3D:
  image: gitlab-registry.mpcdf.mpg.de/khr/docker/gempic/ubuntu2004
  script:
    - mkdir build
    - export BUILD_DIR=`readlink -f ./build`
    - cd scripts
    - bash gempic3D_ci.sh
  tags:
    - avx2
    - docker
