# Simple Docker image with GNU compilers, HDF5, and MPI, taken from SeLaLib.

FROM ubuntu:18.04 

MAINTAINER Katharina Kormann <kako@ipp.mpg.de> 

RUN apt-get update &&\
    apt-get install -y build-essential g++ gfortran cmake git zlib1g-dev libopenmpi-dev libhdf5-openmpi-dev libhdf5-dev libfftw3-dev libopenblas-dev openmpi-bin python3 &&\
    apt-get clean &&\     
    rm -rf /var/lib/apt/lists/* &&\
    rm -f /usr/bin/mpirun &&\     
    echo "#!/bin/bash\n/etc/alternatives/mpirun --allow-run-as-root \$@\n" >/usr/bin/mpirun &&\
    chmod +x /usr/bin/mpirun