"""Visualize coarse and fine domain/interface boxes from AMR level interface data.

Reads interface geometry from a folder generated by
Gempic::Amr::Impl::LevelInterface::write_to_file(folderName). Plots coarse and fine
domains with their interfaces on two side-by-side subplots (2D or 3D depending on
dimensionality).

Usage: python AMR_PlotLevelInterfaces.py <folderName>
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import argparse
import pathlib


def read_file(fileName):
    with open(fileName, "r") as file:
        # discard the first two header lines
        file.readline()
        file.readline()
        content = file.readline()
        return content.strip(")").strip()


def parse_boxes(boxArrayString):
    global DIM
    boxList = []
    boxes = boxArrayString.split(")) ((")
    for box in boxes:
        box = box.split(") (")[:2]

        lower = box[0].strip("()").split(",")
        upper = box[1].strip("()").split(",")

        lower_x = int(lower[0])
        lower_y = int(lower[1])
        upper_x = int(upper[0])
        upper_y = int(upper[1])
        if DIM == 2:
            boxList.append({"low": (lower_x, lower_y), "high": (upper_x, upper_y)})
        else:
            lower_z = int(lower[2])
            upper_z = int(upper[2])
            boxList.append(
                {
                    "low": (lower_x, lower_y, lower_z),
                    "high": (upper_x, upper_y, upper_z),
                }
            )
    return boxList


def plot_boxes(box_data, ax, color="tab:blue", isFine=False, alpha=1):
    global DIM
    if DIM == 2:
        plot_boxes_2D(box_data, ax, color, isFine, alpha)
    else:
        plot_boxes_3D(box_data, ax, color, isFine, alpha)


def plot_boxes_2D(box_data, ax, color="tab:blue", isFine=False, alpha=1):

    if isFine:
        factorX, factorY = 1 / refRatioX, 1 / refRatioY
    else:
        factorX, factorY = 1, 1
    # Loop through each box and extract its coordinates
    for box in box_data:
        lower_x, lower_y = box["low"]
        upper_x, upper_y = box["high"]

        if box["low"] == box["high"]:
            # Single vertex
            ax.scatter(lower_x * factorX, lower_y * factorY, c=color, s=20)
        else:
            # Calculate width and height of the rectangle
            width = upper_x - lower_x + (1 if indexTypeX == "C" else 0)
            height = upper_y - lower_y + (1 if indexTypeY == "C" else 0)

            # Create a rectangle and add it to the plot
            rect = Rectangle(
                (factorX * lower_x, factorY * lower_y),
                factorX * width,
                factorY * height,
                edgecolor=color,
                fill=True,
                facecolor=color,
                linewidth=5,
                alpha=alpha,
                zorder=10,
            )
            ax.add_patch(rect)


def plot_boxes_3D(box_data, ax, color="tab:blue", isFine=False, alpha=1):

    if isFine:
        factorX, factorY, factorZ = 1 / refRatioX, 1 / refRatioY, 1 / refRatioZ
    else:
        factorX, factorY, factorZ = 1, 1, 1
    # Loop through each box and extract its coordinates
    for box in box_data:

        lower_x, lower_y, lower_z = box["low"]
        upper_x, upper_y, upper_z = box["high"]

        if box["low"] == box["high"]:
            # single vertex
            ax.scatter(
                lower_x * factorX, lower_y * factorY, lower_z * factorZ, c=color, s=80
            )
        else:
            # Calculate width and height of the rectangle
            upper_x += 1 if indexTypeX == "C" else 0
            upper_y += 1 if indexTypeY == "C" else 0
            upper_z += 1 if indexTypeZ == "C" else 0

            lower_x *= factorX
            upper_x *= factorX
            lower_y *= factorY
            upper_y *= factorY
            lower_z *= factorZ
            upper_z *= factorZ
            # 8 vertices of the cube
            vertices = np.array(
                [
                    [lower_x, lower_y, lower_z],
                    [upper_x, lower_y, lower_z],
                    [upper_x, upper_y, lower_z],
                    [lower_x, upper_y, lower_z],
                    [lower_x, lower_y, upper_z],
                    [upper_x, lower_y, upper_z],
                    [upper_x, upper_y, upper_z],
                    [lower_x, upper_y, upper_z],
                ]
            )
            # 6 faces of the cube
            faces = [
                [vertices[j] for j in [0, 1, 2, 3]],  # bottom
                [vertices[j] for j in [4, 5, 6, 7]],  # top
                [vertices[j] for j in [0, 1, 5, 4]],  # front
                [vertices[j] for j in [2, 3, 7, 6]],  # back
                [vertices[j] for j in [1, 2, 6, 5]],  # right
                [vertices[j] for j in [4, 7, 3, 0]],  # left
            ]

            cube = Poly3DCollection(
                faces, facecolors=color, alpha=alpha, edgecolors=color
            )
            ax.add_collection3d(cube)


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "folder",
        type=pathlib.Path,
        help="Path to folder containing AMR level interface data",
    )
    args = parser.parse_args()
    folder_path = args.folder

    # Read index type and refinement ratio from file
    with open(folder_path / "IndexType.txt") as file:
        indexTypeX, indexTypeY, *indexTypeZ = file.readline()[1:-2].split(",")
        DIM = 3 if indexTypeZ else 2
    with open(folder_path / "RefinementRatio.txt") as file:
        refRatioX, refRatioY, *refRatioZ = file.readline()[1:-2].split(",")
    refRatioX, refRatioY = int(refRatioX), int(refRatioY)
    if DIM == 3:
        refRatioZ = int(refRatioZ[0])

    colors = ["tab:blue", "tab:orange", "tab:green", "tab:red"]

    fig = plt.figure()

    if DIM == 3:
        ax1 = fig.add_subplot(121, projection="3d")
        ax2 = fig.add_subplot(122, projection="3d")
    else:
        ax1 = fig.add_subplot(121)
        ax2 = fig.add_subplot(122)

    coarseDomain = read_file(folder_path / "CoarseDomain.txt")
    fineDomain = read_file(folder_path / "FineDomain.txt")

    coarse = read_file(folder_path / "CoarseInterface.txt")
    fine = read_file(folder_path / "FineInterface.txt")

    if DIM == 3:
        alphaDomain = 0.05
        alphaInterface = 0.25
    else:
        alphaDomain = 0.25
        alphaInterface = 0.75

    plot_boxes(parse_boxes(coarseDomain), ax1, colors[0], alpha=alphaDomain)
    plot_boxes(parse_boxes(fineDomain), ax1, colors[1], isFine=True, alpha=alphaDomain)
    plot_boxes(parse_boxes(coarseDomain), ax2, colors[0], alpha=alphaDomain)
    plot_boxes(parse_boxes(fineDomain), ax2, colors[1], isFine=True, alpha=alphaDomain)

    plot_boxes(parse_boxes(coarse), ax1, colors[2], alpha=alphaInterface)
    plot_boxes(parse_boxes(fine), ax2, colors[3], isFine=True, alpha=alphaInterface)

    ax1.set_title("Coarse interface")
    ax2.set_title("Fine interface")

    ax1.set_xlabel("x")
    ax1.set_ylabel("y")
    ax2.set_xlabel("x")
    ax2.set_ylabel("y")

    if DIM == 2:
        ax1.set_aspect("equal")
        ax2.set_aspect("equal")
    else:
        ax1.set_box_aspect([1, 1, 1])
        ax2.set_box_aspect([1, 1, 1])
        ax1.set_zlabel("z")
        ax2.set_zlabel("z")

    plt.show()
