message(STATUS "--GEMPIC-CompilerID: ${CMAKE_CXX_COMPILER_ID}")
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU.*")
  # gcc
  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -funroll-all-loops -mavx2  -march=native")
  set(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_CXX_FLAGS_DEBUG} -Wall")
  message(STATUS "--GEMPIC-Compiler: GNU")
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Intel.*")
  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -funroll-all-loops -xHost -zmm-usage=high -Ofast -qopt-prefetch=2 -mcmodel=large") # or try 4 for prefetch
  set(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_CXX_FLAGS_DEBUG} -Wall")
  message(STATUS "--GEMPIC-Compiler: Intel")
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang.*")
  # Clang 
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Wall -Wextra")
  message(STATUS "--GEMPIC-Compiler: Clang")
else()
  message(STATUS "--GEMPIC-Compiler: Unknown compiler")
endif()

if(GEMPIC_USE_CUDA)
  add_definitions(-DGEMPIC_GPU)
  if(($ENV{HOST} MATCHES "cobra*") OR ($ENV{HOST} MATCHES "raven*"))
    if(CMAKE_CXX_COMPILER_ID MATCHES "Intel.*")  
      set(CMAKE_CUDA_FLAGS "--Werror cross-execution-space-call --expt-extended-lambda --expt-relaxed-constexpr -ccbin=mpiicpc -I${CUDA_HOME}/include -L${CUDA_HOME}/lib64 -lcurand")
      set(CMAKE_CUDA_FLAGS_RELEASE "--Werror cross-execution-space-call --expt-extended-lambda --expt-relaxed-constexpr -ccbin=mpiicpc -I${CUDA_HOME}/include -L${CUDA_HOME}/lib64 -lcurand -arch sm_80")
      set(CMAKE_CUDA_FLAGS_DEBUG   "--Werror cross-execution-space-call --expt-extended-lambda --expt-relaxed-constexpr -ccbin=mpiicpc -I${CUDA_HOME}/include -L${CUDA_HOME}/lib64 -lcurand -arch sm_80")
    endif()
  endif()

  find_package(CUDAToolkit REQUIRED)
  set(CMAKE_CUDA_FLAGS "-lcusparse -lcurand" )
endif()
